### ISSUE TITLE
Serialize LANGSXP values.

### ISSUE THREAD

**Issue by fghibellini** [PRL-PRG/genthat#2]

**Comment by mvacha** [comment]
### Research
Formula = lang. Expression + environment containing the variables not found in the supplied data argument (see questions).
Formula's AST is comprised of the following node types:
1. Function
1.1. +, -, : and other special functions for constructing formulas
1.2. Any other R function (e.g. log)
2. Variable
2.1. Column name from dataset
2.2. Vector bound in formula’s environment
2.3. package::otherDataset$col

### Current status:
- LANGEXPRs get serialized as a string without values.
- Unknown state of (un)evaluation.
- Not covered by tests. 

### Tasks:
- [ ] Check if we are forcing evaluation of formulae and whether it breaks them.
- [ ] Analyze traces of different formulae.
- [ ] Extract list of captured variables from enclosing environment.
- [ ] Wait for environment serialization.
- [ ] Add tests

### Questions:
Is there relevant case to use formula without accompanying data frame?
